name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Download Toolchain
        run: |
          mkdir ${GITHUB_WORKSPACE}/toolchain/clang-r416183b
          curl "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/428d18d9732aa7ebfcaed87a582d86155db878d4/clang-r416183b.tar.gz" | tar --directory=${GITHUB_WORKSPACE}/toolchain/clang-r416183b --extract --gzip

      - name: Build Kernel
        run: |
          ./build_kernel.sh

      - name: Package Kernel
        run: ./package_kernel.sh

      - uses: actions/upload-artifact@v7
        with:
          path: UPDATE-AnyKernel3.zip
